import type { Locale } from "../Hero/hero.types";
import type { SelectedWorkCopy } from "./selectedWork.types";

const technologies = {
  nl2map: ["Python", "Scikit-learn", "GeoPandas", "Shapely"],
  se4g: ["Python", "Dash", "Flask", "Plotly", "Folium", "GeoPandas", "PostgreSQL / PostGIS"],
  landslide: ["QGIS", "Random Forest", "Remote sensing", "Python", "OpenLayers", "WebGIS"],
};

export const selectedWorkCopy: Record<Locale, SelectedWorkCopy> = {
  en: {
    eyebrow: "03 / Selected work",
    heading: "Selected Work",
    supporting: "Three projects. One through-line: spatial evidence becomes a usable system.",
    workflowVisualizationsLabel: "Project workflow visualizations",
    illustrationLabel: "Workflow illustration",
    actualEvidenceLabel: "Real project output",
    caseStudyCta: "Read case study",
    fields: {
      problem: "Problem",
      role: "Role",
      input: "Data / Input",
      approach: "Approach",
      technologies: "Technologies",
      output: "Output",
      evidence: "Evidence",
    },
    visualLabels: {
      prompt: "Prompt",
      features: "Text features",
      model: "Classifier",
      operation: "Operation",
      mapState: "Map state",
      originalMap: "Original map",
      generalizedMap: "Generalized map",
      sourceData: "Source data",
      spatialDatabase: "Spatial database",
      api: "API layer",
      dashboard: "Dashboard",
      terrain: "Terrain",
      variables: "Variables",
      susceptibility: "Susceptibility",
    },
    projects: [
      {
        slug: "nl2map",
        number: "01",
        shortTitle: "NL2MAP",
        title: "Inferring Map Generalization Operations from User Prompts",
        context: "MSc thesis research · University of Bonn + Politecnico di Milano",
        problem: "Translate natural-language descriptions of visible map changes into cartographic generalization operations.",
        role: "MSc thesis researcher and implementation author.",
        input: "User-written prompts paired with original and generalized building maps.",
        approach: "Turn prompt language into model-ready features, classify the described operation, and relate it to the resulting map state.",
        technologies: technologies.nl2map,
        output: "A research workflow and user-study interface connecting descriptions to map transformations.",
        evidence: "The paired maps shown here come directly from the public thesis user-study repository.",
        evidenceLinks: [
          { label: "Open study", href: "https://amirdonyadide.github.io/Thesis_UserStudy/" },
          { label: "Source repository", href: "https://github.com/AmirDonyadide/Thesis_UserStudy" },
        ],
      },
      {
        slug: "se4g",
        number: "02",
        shortTitle: "SE4G",
        title: "Geoinformatics Data Visualization Dashboard",
        context: "Software Engineering for Geoinformatics · Four-person team project",
        problem: "Make geospatial hazard indicators and event-location data easier to inspect through one interactive application.",
        role: "Team project contributor; the public design document names four contributors.",
        input: "Italian municipality geometries, hydrogeological indicators, Olympic-event locations, and user reports.",
        approach: "Prepare spatial data in PostgreSQL/PostGIS, expose it through Flask endpoints, and connect maps, tables, and plots in Dash.",
        technologies: technologies.se4g,
        output: "An interactive dashboard with city selection, Folium maps, indicator tables, and Plotly charts.",
        evidence: "Repository code and design documents contain the implemented data flow and interface states.",
        evidenceLinks: [
          { label: "View repository", href: "https://github.com/AmirDonyadide/SE4G" },
        ],
      },
      {
        slug: "landslide",
        number: "03",
        shortTitle: "Landslide",
        title: "AI-Based Landslide Susceptibility Mapping",
        context: "MSc GIS course project · Three-person team",
        problem: "Assess where terrain and environmental conditions indicate higher landslide susceptibility in a Bergamo study area.",
        role: "Team project contributor; Amirhossein is one of three named contributors.",
        input: "DTM, DUSAF land use, NDVI, river and road buffers, faults, terrain derivatives, and landslide inventory data.",
        approach: "Standardize raster layers, train a Random Forest classifier in QGIS, derive a susceptibility surface, validate it, and publish it through WebGIS.",
        technologies: technologies.landslide,
        output: "A susceptibility raster, exposure analysis, validation workflow, and interactive WebGIS.",
        evidence: "The terrain and susceptibility maps shown here are actual outputs from the public project repository.",
        evidenceLinks: [
          { label: "Open project", href: "https://amirdonyadide.github.io/GIS-Course-Polimi-2024/" },
          { label: "Source repository", href: "https://github.com/AmirDonyadide/GIS-Course-Polimi-2024" },
        ],
      },
    ],
  },
  de: {
    eyebrow: "03 / Ausgewählte Projekte",
    heading: "Ausgewählte Projekte",
    supporting: "Drei Projekte mit einem roten Faden: Aus räumlichen Daten werden nutzbare Systeme.",
    workflowVisualizationsLabel: "Visualisierungen der Projektabläufe",
    illustrationLabel: "Workflow-Illustration",
    actualEvidenceLabel: "Reales Projektergebnis",
    caseStudyCta: "Fallstudie lesen",
    fields: {
      problem: "Problem",
      role: "Rolle",
      input: "Daten / Input",
      approach: "Ansatz",
      technologies: "Technologien",
      output: "Ergebnis",
      evidence: "Nachweis",
    },
    visualLabels: {
      prompt: "Prompt",
      features: "Textmerkmale",
      model: "Klassifikator",
      operation: "Operation",
      mapState: "Kartenzustand",
      originalMap: "Originalkarte",
      generalizedMap: "Generalisierte Karte",
      sourceData: "Quelldaten",
      spatialDatabase: "Geodatenbank",
      api: "API-Schicht",
      dashboard: "Dashboard",
      terrain: "Gelände",
      variables: "Variablen",
      susceptibility: "Suszeptibilität",
    },
    projects: [
      {
        slug: "nl2map",
        number: "01",
        shortTitle: "NL2MAP",
        title: "Inferring Map Generalization Operations from User Prompts",
        context: "Masterarbeit · Universität Bonn + Politecnico di Milano",
        problem: "Natürlichsprachige Beschreibungen sichtbarer Kartenänderungen in kartografische Generalisierungsoperationen übersetzen.",
        role: "Masterand und Autor der Forschungsimplementierung.",
        input: "Von Nutzenden formulierte Prompts mit originalen und generalisierten Gebäudekarten.",
        approach: "Prompt-Sprache in modellierbare Merkmale überführen, die beschriebene Operation klassifizieren und dem resultierenden Kartenzustand zuordnen.",
        technologies: technologies.nl2map,
        output: "Ein Forschungsworkflow und eine User-Study-Oberfläche, die Beschreibungen mit Kartentransformationen verbindet.",
        evidence: "Die gezeigten Kartenpaare stammen direkt aus dem öffentlichen Repository der Thesis-Studie.",
        evidenceLinks: [
          { label: "Studie öffnen", href: "https://amirdonyadide.github.io/Thesis_UserStudy/" },
          { label: "Quellcode", href: "https://github.com/AmirDonyadide/Thesis_UserStudy" },
        ],
      },
      {
        slug: "se4g",
        number: "02",
        shortTitle: "SE4G",
        title: "Geoinformatics Data Visualization Dashboard",
        context: "Software Engineering for Geoinformatics · Vierköpfiges Teamprojekt",
        problem: "Räumliche Gefahrenindikatoren und Veranstaltungsorte in einer interaktiven Anwendung besser untersuchbar machen.",
        role: "Beitrag zum Teamprojekt; das öffentliche Design-Dokument nennt vier Mitwirkende.",
        input: "Geometrien italienischer Gemeinden, hydrogeologische Indikatoren, olympische Veranstaltungsorte und Nutzerberichte.",
        approach: "Geodaten in PostgreSQL/PostGIS aufbereiten, über Flask-Endpunkte bereitstellen und Karten, Tabellen und Diagramme in Dash verbinden.",
        technologies: technologies.se4g,
        output: "Ein interaktives Dashboard mit Stadtauswahl, Folium-Karten, Indikatortabellen und Plotly-Diagrammen.",
        evidence: "Repository-Code und Design-Dokumente belegen Datenfluss und implementierte Oberflächenzustände.",
        evidenceLinks: [
          { label: "Repository ansehen", href: "https://github.com/AmirDonyadide/SE4G" },
        ],
      },
      {
        slug: "landslide",
        number: "03",
        shortTitle: "Landslide",
        title: "AI-Based Landslide Susceptibility Mapping",
        context: "MSc-GIS-Kursprojekt · Dreiköpfiges Team",
        problem: "Gebiete identifizieren, in denen Gelände- und Umweltbedingungen auf erhöhte Hangrutschungsanfälligkeit hinweisen.",
        role: "Beitrag zum Teamprojekt; Amirhossein ist einer von drei genannten Mitwirkenden.",
        input: "DTM, DUSAF-Landnutzung, NDVI, Fluss- und Straßenpuffer, Störungen, Geländederivate und Hangrutschungsinventar.",
        approach: "Raster vereinheitlichen, einen Random-Forest-Klassifikator in QGIS trainieren, eine Suszeptibilitätsfläche ableiten, validieren und als WebGIS veröffentlichen.",
        technologies: technologies.landslide,
        output: "Suszeptibilitätsraster, Expositionsanalyse, Validierungsworkflow und interaktives WebGIS.",
        evidence: "Gelände- und Suszeptibilitätskarte sind reale Ergebnisse aus dem öffentlichen Projekt-Repository.",
        evidenceLinks: [
          { label: "Projekt öffnen", href: "https://amirdonyadide.github.io/GIS-Course-Polimi-2024/" },
          { label: "Quellcode", href: "https://github.com/AmirDonyadide/GIS-Course-Polimi-2024" },
        ],
      },
    ],
  },
  it: {
    eyebrow: "03 / Progetti selezionati",
    heading: "Progetti selezionati",
    supporting: "Tre progetti, un unico filo conduttore: dai dati spaziali a sistemi utilizzabili.",
    workflowVisualizationsLabel: "Visualizzazioni dei flussi di progetto",
    illustrationLabel: "Illustrazione del flusso",
    actualEvidenceLabel: "Output reale del progetto",
    caseStudyCta: "Leggi il caso studio",
    fields: {
      problem: "Problema",
      role: "Ruolo",
      input: "Dati / Input",
      approach: "Approccio",
      technologies: "Tecnologie",
      output: "Output",
      evidence: "Evidenza",
    },
    visualLabels: {
      prompt: "Prompt",
      features: "Feature testuali",
      model: "Classificatore",
      operation: "Operazione",
      mapState: "Stato mappa",
      originalMap: "Mappa originale",
      generalizedMap: "Mappa generalizzata",
      sourceData: "Dati sorgente",
      spatialDatabase: "Database spaziale",
      api: "Livello API",
      dashboard: "Dashboard",
      terrain: "Terreno",
      variables: "Variabili",
      susceptibility: "Suscettibilità",
    },
    projects: [
      {
        slug: "nl2map",
        number: "01",
        shortTitle: "NL2MAP",
        title: "Inferring Map Generalization Operations from User Prompts",
        context: "Tesi magistrale · Università di Bonn + Politecnico di Milano",
        problem: "Tradurre descrizioni in linguaggio naturale dei cambiamenti visibili in operazioni di generalizzazione cartografica.",
        role: "Ricercatore di tesi e autore dell'implementazione.",
        input: "Prompt scritti dagli utenti abbinati a mappe di edifici originali e generalizzate.",
        approach: "Trasformare il linguaggio dei prompt in feature utilizzabili dal modello, classificare l'operazione descritta e collegarla allo stato finale della mappa.",
        technologies: technologies.nl2map,
        output: "Un workflow di ricerca e un'interfaccia di user study che collegano descrizioni e trasformazioni cartografiche.",
        evidence: "Le coppie di mappe mostrate provengono direttamente dal repository pubblico dello studio di tesi.",
        evidenceLinks: [
          { label: "Apri lo studio", href: "https://amirdonyadide.github.io/Thesis_UserStudy/" },
          { label: "Repository sorgente", href: "https://github.com/AmirDonyadide/Thesis_UserStudy" },
        ],
      },
      {
        slug: "se4g",
        number: "02",
        shortTitle: "SE4G",
        title: "Geoinformatics Data Visualization Dashboard",
        context: "Software Engineering for Geoinformatics · Progetto in team di quattro persone",
        problem: "Rendere più accessibili indicatori di pericolosità geospaziale e dati sugli eventi in un'unica applicazione interattiva.",
        role: "Contributore al progetto di gruppo; il design document pubblico indica quattro partecipanti.",
        input: "Geometrie dei comuni italiani, indicatori idrogeologici, sedi olimpiche e segnalazioni degli utenti.",
        approach: "Preparare i dati spaziali in PostgreSQL/PostGIS, esporli tramite endpoint Flask e collegare mappe, tabelle e grafici in Dash.",
        technologies: technologies.se4g,
        output: "Una dashboard interattiva con selezione delle città, mappe Folium, tabelle di indicatori e grafici Plotly.",
        evidence: "Codice e documenti di progetto mostrano il flusso dati e gli stati dell'interfaccia implementata.",
        evidenceLinks: [
          { label: "Vedi repository", href: "https://github.com/AmirDonyadide/SE4G" },
        ],
      },
      {
        slug: "landslide",
        number: "03",
        shortTitle: "Landslide",
        title: "AI-Based Landslide Susceptibility Mapping",
        context: "Progetto GIS magistrale · Team di tre persone",
        problem: "Valutare dove le condizioni del terreno e dell'ambiente indicano una maggiore suscettibilità alle frane nell'area di Bergamo.",
        role: "Contributore al progetto di gruppo; Amirhossein è uno dei tre partecipanti indicati.",
        input: "DTM, uso del suolo DUSAF, NDVI, buffer di fiumi e strade, faglie, derivate del terreno e inventario delle frane.",
        approach: "Uniformare i raster, addestrare un classificatore Random Forest in QGIS, derivare una superficie di suscettibilità, validarla e pubblicarla tramite WebGIS.",
        technologies: technologies.landslide,
        output: "Raster di suscettibilità, analisi dell'esposizione, workflow di validazione e WebGIS interattivo.",
        evidence: "Le mappe del terreno e della suscettibilità sono output reali del repository pubblico del progetto.",
        evidenceLinks: [
          { label: "Apri progetto", href: "https://amirdonyadide.github.io/GIS-Course-Polimi-2024/" },
          { label: "Repository sorgente", href: "https://github.com/AmirDonyadide/GIS-Course-Polimi-2024" },
        ],
      },
    ],
  },
};
