import type { Locale } from "../Hero/hero.types";
import type { AdditionalWorkCopy } from "./additionalWork.types";

const projects = {
  en: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Remote sensing toolkit",
      description: "Process Landsat 7/8/9 scenes: metadata, band composition, reprojection, indices, and organization.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Public repository",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Raster simulation",
      description: "Modify rasters with vector masks, percentage changes, and replacements; validate CRS and normalize values.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Public repository",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Responsive web application",
      description: "Contributed frontend and UX for user profiles and database-driven content.",
      technologies: ["JavaScript", "Responsive UI", "Database"],
      context: "Repository not public",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Computer vision coursework",
      description: "KIT team project comparing a custom CNN and fine-tuned ResNet18 for binary image classification.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Public repository",
    },
  ],
  de: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Fernerkundungs-Toolkit",
      description: "Landsat-7/8/9-Szenen verarbeiten: Metadaten, Bandkombinationen, Reprojektion, Indizes und Organisation.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Öffentliches Repository",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Rastersimulation",
      description: "Raster per Vektormaske, Prozentänderung oder Ersetzung bearbeiten; CRS prüfen und Werte normalisieren.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Öffentliches Repository",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Responsive Webanwendung",
      description: "Frontend und UX für Nutzerprofile und datenbankgestützte Inhalte mitentwickelt.",
      technologies: ["JavaScript", "Responsive UI", "Datenbank"],
      context: "Repository nicht öffentlich",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Computer-Vision-Kursprojekt",
      description: "KIT-Teamprojekt: eigenes CNN und feinabgestimmtes ResNet18 für binäre Bildklassifikation vergleichen.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Öffentliches Repository",
    },
  ],
  it: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Toolkit di telerilevamento",
      description: "Elaborare scene Landsat 7/8/9: metadati, composizione delle bande, riproiezione, indici e organizzazione.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Repository pubblico",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Simulazione raster",
      description: "Modificare raster con maschere vettoriali, variazioni percentuali e sostituzioni; verificare CRS e normalizzare valori.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Repository pubblico",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Applicazione web responsive",
      description: "Contributo frontend e UX per profili utente e contenuti da database.",
      technologies: ["JavaScript", "Responsive UI", "Database"],
      context: "Repository non pubblico",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Progetto didattico di computer vision",
      description: "Progetto di gruppo KIT: confronto tra CNN personalizzata e ResNet18 con fine-tuning per classificazione binaria.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Repository pubblico",
    },
  ],
};

export const additionalWorkCopy: Record<Locale, AdditionalWorkCopy> = {
  en: {
    eyebrow: "04 / Project index",
    heading: "Additional Work",
    workflowLabel: "Conceptual workflow",
    openProject: "Open repository",
    privateProject: "View workflow",
    projectIndexLabel: "Additional project index",
    technologiesLabel: "Technologies",
    previewLabels: {
      landsat: ["Metadata", "Band stack", "Reproject", "Index output"],
      layeralterator: ["Vector rules", "Raster layers", "Validate", "Altered rasters"],
      poliyoga: ["Responsive UI", "Profiles", "Database features", "Dynamic content"],
      classifier: ["Image dataset", "CNN / ResNet18", "Evaluate", "Confusion matrix"],
    },
    projects: projects.en,
  },
  de: {
    eyebrow: "04 / Projektindex",
    heading: "Weitere Projekte",
    workflowLabel: "Konzeptioneller Ablauf",
    openProject: "Repository öffnen",
    privateProject: "Ablauf ansehen",
    projectIndexLabel: "Index weiterer Projekte",
    technologiesLabel: "Technologien",
    previewLabels: {
      landsat: ["Metadaten", "Bandstapel", "Reprojektion", "Index-Output"],
      layeralterator: ["Vektorregeln", "Rasterebenen", "Prüfung", "Geänderte Raster"],
      poliyoga: ["Responsive UI", "Profile", "Datenbankfunktionen", "Dynamische Inhalte"],
      classifier: ["Bilddatensatz", "CNN / ResNet18", "Evaluation", "Konfusionsmatrix"],
    },
    projects: projects.de,
  },
  it: {
    eyebrow: "04 / Indice progetti",
    heading: "Altri progetti",
    workflowLabel: "Flusso concettuale",
    openProject: "Apri repository",
    privateProject: "Vedi il flusso",
    projectIndexLabel: "Indice degli altri progetti",
    technologiesLabel: "Tecnologie",
    previewLabels: {
      landsat: ["Metadati", "Bande", "Riproiezione", "Output indice"],
      layeralterator: ["Regole vettoriali", "Layer raster", "Validazione", "Raster modificati"],
      poliyoga: ["UI responsive", "Profili", "Funzioni database", "Contenuti dinamici"],
      classifier: ["Dataset immagini", "CNN / ResNet18", "Valutazione", "Matrice di confusione"],
    },
    projects: projects.it,
  },
};
