import type { Locale } from "../Hero/hero.types";
import type { AdditionalWorkCopy } from "./additionalWork.types";

const projects = {
  en: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Remote sensing toolkit",
      description: "Reusable Python library for Landsat 7, 8, and 9 metadata, band composition, reprojection, indices, and scene organization.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Public repository",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Raster simulation",
      description: "Rule-driven raster modification from vector masks, with percentage and replacement operations, CRS checks, and normalization.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Public repository",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Responsive web application",
      description: "Frontend and UX contribution to a responsive platform with profiles, database-backed features, and dynamic content.",
      technologies: ["JavaScript", "Responsive UI", "Database-backed features"],
      context: "Repository not public",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Computer vision coursework",
      description: "KIT group coursework comparing a custom CNN with a fine-tuned ResNet18 for binary image classification and evaluation.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Public repository",
    },
  ],
  de: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Fernerkundungs-Toolkit",
      description: "Wiederverwendbare Python-Bibliothek für Metadaten, Bandkombinationen, Reprojektion, Indizes und Szenenorganisation von Landsat 7, 8 und 9.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Öffentliches Repository",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Rastersimulation",
      description: "Regelbasierte Rasteränderung über Vektormasken mit prozentualen und ersetzenden Operationen, CRS-Prüfung und Normalisierung.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Öffentliches Repository",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Responsive Webanwendung",
      description: "Frontend- und UX-Beitrag zu einer responsiven Plattform mit Profilen, datenbankgestützten Funktionen und dynamischen Inhalten.",
      technologies: ["JavaScript", "Responsive UI", "Datenbankgestützte Funktionen"],
      context: "Repository nicht öffentlich",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Computer-Vision-Kursprojekt",
      description: "KIT-Gruppenarbeit zum Vergleich eines eigenen CNN mit einem feinabgestimmten ResNet18 für binäre Bildklassifikation und Evaluation.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Öffentliches Repository",
    },
  ],
  it: [
    {
      id: "landsat" as const,
      number: "01",
      title: "LandsatToolkit",
      type: "Toolkit di telerilevamento",
      description: "Libreria Python riutilizzabile per metadati, composizione delle bande, riproiezione, indici e organizzazione delle scene Landsat 7, 8 e 9.",
      technologies: ["Python", "Rasterio", "NumPy"],
      href: "https://github.com/AmirDonyadide/LandsatToolkit",
      context: "Repository pubblico",
    },
    {
      id: "layeralterator" as const,
      number: "02",
      title: "LayerAlterator",
      type: "Simulazione raster",
      description: "Modifica raster basata su regole e maschere vettoriali, con operazioni percentuali e di sostituzione, controlli CRS e normalizzazione.",
      technologies: ["Python", "Rasterio", "GeoPandas", "NumPy"],
      href: "https://github.com/AmirDonyadide/LayerAlterator",
      context: "Repository pubblico",
    },
    {
      id: "poliyoga" as const,
      number: "03",
      title: "PoliYoga",
      type: "Applicazione web responsive",
      description: "Contributo frontend e UX a una piattaforma responsive con profili, funzioni collegate al database e contenuti dinamici.",
      technologies: ["JavaScript", "Responsive UI", "Funzioni collegate al database"],
      context: "Repository non pubblico",
    },
    {
      id: "classifier" as const,
      number: "04",
      title: "Car / Not Car Classifier",
      type: "Progetto didattico di computer vision",
      description: "Progetto di gruppo al KIT che confronta una CNN personalizzata e ResNet18 ottimizzato per classificazione binaria e valutazione delle immagini.",
      technologies: ["PyTorch", "Torchvision", "Scikit-learn", "TensorBoard"],
      href: "https://github.com/AmirDonyadide/DL4CVRS",
      context: "Repository pubblico",
    },
  ],
};

export const additionalWorkCopy: Record<Locale, AdditionalWorkCopy> = {
  en: {
    eyebrow: "04 / Project index",
    heading: "Additional Work",
    supporting: "Smaller systems. The same engineering thread: spatial inputs, explicit processing, and usable outputs.",
    workflowLabel: "Conceptual workflow — not a project screenshot",
    openProject: "Open repository",
    privateProject: "View workflow",
    projectIndexLabel: "Additional project index",
    technologiesLabel: "Technologies",
    previewLabels: {
      landsat: ["Metadata", "Band stack", "Reproject", "Index output"],
      layeralterator: ["Vector rules", "Raster layers", "Validate", "Altered rasters"],
      poliyoga: ["Responsive UI", "Profiles", "Database features", "Dynamic content"],
      classifier: ["Image dataset", "CNN / ResNet18", "Evaluate", "Confusion matrix"],
    },
    projects: projects.en,
  },
  de: {
    eyebrow: "04 / Projektindex",
    heading: "Weitere Projekte",
    supporting: "Kleinere Systeme mit demselben technischen Faden: räumliche Inputs, explizite Verarbeitung und nutzbare Ergebnisse.",
    workflowLabel: "Konzeptioneller Ablauf — kein Projekt-Screenshot",
    openProject: "Repository öffnen",
    privateProject: "Ablauf ansehen",
    projectIndexLabel: "Index weiterer Projekte",
    technologiesLabel: "Technologien",
    previewLabels: {
      landsat: ["Metadaten", "Bandstapel", "Reprojektion", "Index-Output"],
      layeralterator: ["Vektorregeln", "Rasterebenen", "Prüfung", "Geänderte Raster"],
      poliyoga: ["Responsive UI", "Profile", "Datenbankfunktionen", "Dynamische Inhalte"],
      classifier: ["Bilddatensatz", "CNN / ResNet18", "Evaluation", "Konfusionsmatrix"],
    },
    projects: projects.de,
  },
  it: {
    eyebrow: "04 / Indice progetti",
    heading: "Altri progetti",
    supporting: "Sistemi più compatti, con lo stesso filo tecnico: input spaziali, elaborazione esplicita e output utilizzabili.",
    workflowLabel: "Flusso concettuale — non è uno screenshot del progetto",
    openProject: "Apri repository",
    privateProject: "Vedi il flusso",
    projectIndexLabel: "Indice degli altri progetti",
    technologiesLabel: "Tecnologie",
    previewLabels: {
      landsat: ["Metadati", "Bande", "Riproiezione", "Output indice"],
      layeralterator: ["Regole vettoriali", "Layer raster", "Validazione", "Raster modificati"],
      poliyoga: ["UI responsive", "Profili", "Funzioni database", "Contenuti dinamici"],
      classifier: ["Dataset immagini", "CNN / ResNet18", "Valutazione", "Matrice di confusione"],
    },
    projects: projects.it,
  },
};
