import type { ExperienceCopyByLocale } from "./experience.types";

export const experienceCopy: ExperienceCopyByLocale = {
  en: {
    eyebrow: "05 / Experience",
    heading: "Experience",
    supporting: "Research, data, and software in practice.",
    timelineLabel: "Career trajectory from 2021 to the current role",
    pathCurrentLabel: "CURRENT",
    pathOriginLabel: "ORIGIN · 2021",
    currentRole: "Current role",
    responsibilitiesLabel: "Responsibilities",
    focusLabel: "Focus",
    roles: [
      {
        id: "safe",
        date: "August 2026 – Present",
        role: "Research Assistant",
        organization: "Leibniz Institute for Financial Research SAFE",
        location: "Frankfurt am Main, Germany",
        responsibilities: [
          "Prepare and process geospatial and environmental datasets through reproducible Python workflows.",
          "Support large-scale address, geocoding, and location-linkage workflows for research.",
          "Link corporate and location information with environmental or remote-sensing data.",
          "Support research-computing workflows for larger spatial datasets.",
        ],
        focus: ["Python", "Geospatial data engineering", "Environmental data", "Research computing"],
        current: true,
        pathLabel: "SAFE · Frankfurt",
      },
      {
        id: "iip",
        date: "July 2025 – March 2026",
        role: "GIS & Data Analyst, Research Assistant",
        organization: "IIP, Karlsruhe Institute of Technology (KIT)",
        location: "Karlsruhe, Germany",
        responsibilities: [
          "Developed Python-based data pipelines for energy and mobility data processing.",
          "Performed spatial analyses supporting energy-demand and decarbonization models.",
          "Built interactive dashboards with map integration for applied research workflows.",
        ],
        focus: ["Python", "Spatial analysis", "Energy and mobility data", "Dashboards"],
        pathLabel: "IIP · KIT",
      },
      {
        id: "nova",
        date: "July 2025 – December 2025",
        role: "Web Developer, Research Assistant",
        organization: "KIT nova",
        location: "Karlsruhe, Germany",
        responsibilities: [
          "Contributed to web applications with a focus on functionality and usability.",
          "Supported VR/AR projects for digital and interactive applications.",
          "Contributed to geospatial visualizations and digital map solutions.",
        ],
        focus: ["Web applications", "VR/AR", "Geovisualization", "Digital maps"],
        pathLabel: "KIT nova",
      },
      {
        id: "fartak",
        date: "May 2021 – September 2021",
        role: "Intern",
        organization: "Naghsheh Gostaran Fartak Co.",
        responsibilities: [
          "Supported surveying, photogrammetry, and GIS projects in a practical work environment.",
          "Assisted with data collection, spatial analysis, and technical implementation.",
          "Applied AutoCAD and GIS tools for creating and processing geospatial data.",
        ],
        focus: ["Surveying", "Photogrammetry", "AutoCAD", "GIS"],
        pathLabel: "Fartak Co.",
      },
    ],
  },
  de: {
    eyebrow: "05 / Erfahrung",
    heading: "Erfahrung",
    supporting: "Forschung, Daten und Software in der Praxis.",
    timelineLabel: "Beruflicher Weg von 2021 bis zur aktuellen Position",
    pathCurrentLabel: "AKTUELL",
    pathOriginLabel: "ANFANG · 2021",
    currentRole: "Aktuelle Position",
    responsibilitiesLabel: "Aufgaben",
    focusLabel: "Schwerpunkte",
    roles: [
      {
        id: "safe",
        date: "August 2026 – heute",
        role: "Research Assistant",
        organization: "Leibniz Institute for Financial Research SAFE",
        location: "Frankfurt am Main, Deutschland",
        responsibilities: [
          "Geospatiale und umweltbezogene Datensätze in reproduzierbaren Python-Workflows aufbereiten und verarbeiten.",
          "Großskalige Adress-, Geocoding- und Standortverknüpfungs-Workflows für die Forschung unterstützen.",
          "Unternehmens- und Standortinformationen mit Umwelt- oder Fernerkundungsdaten verknüpfen.",
          "Research-Computing-Workflows für größere räumliche Datensätze unterstützen.",
        ],
        focus: ["Python", "Geodaten-Engineering", "Umweltdaten", "Research Computing"],
        current: true,
        pathLabel: "SAFE · Frankfurt",
      },
      {
        id: "iip",
        date: "Juli 2025 – März 2026",
        role: "GIS- und Datenanalyst, Hilfswissenschaftler",
        organization: "IIP, Karlsruher Institut für Technologie (KIT)",
        location: "Karlsruhe, Deutschland",
        responsibilities: [
          "Python-basierte Datenpipelines für die Verarbeitung von Energie- und Mobilitätsdaten entwickelt.",
          "Räumliche Analysen zur Unterstützung von Energiebedarfs- und Dekarbonisierungsmodellen durchgeführt.",
          "Interaktive Dashboards mit Kartenintegration für angewandte Forschungsabläufe entwickelt.",
        ],
        focus: ["Python", "Räumliche Analyse", "Energie- und Mobilitätsdaten", "Dashboards"],
        pathLabel: "IIP · KIT",
      },
      {
        id: "nova",
        date: "Juli 2025 – Dezember 2025",
        role: "Webentwickler, Hilfswissenschaftler",
        organization: "KIT nova",
        location: "Karlsruhe, Deutschland",
        responsibilities: [
          "Webanwendungen mit Fokus auf Funktionalität und Benutzerfreundlichkeit mitentwickelt.",
          "VR/AR-Projekte für digitale und interaktive Anwendungen unterstützt.",
          "Zu Geovisualisierungen und digitalen Kartenlösungen beigetragen.",
        ],
        focus: ["Webanwendungen", "VR/AR", "Geovisualisierung", "Digitale Karten"],
        pathLabel: "KIT nova",
      },
      {
        id: "fartak",
        date: "Mai 2021 – September 2021",
        role: "Praktikant",
        organization: "Naghsheh Gostaran Fartak Co.",
        responsibilities: [
          "Vermessungs-, Photogrammetrie- und GIS-Projekte in einem praktischen Arbeitsumfeld unterstützt.",
          "Bei Datenerhebung, räumlicher Analyse und technischer Umsetzung mitgewirkt.",
          "AutoCAD und GIS-Werkzeuge zur Erstellung und Verarbeitung von Geodaten eingesetzt.",
        ],
        focus: ["Vermessung", "Photogrammetrie", "AutoCAD", "GIS"],
        pathLabel: "Fartak Co.",
      },
    ],
  },
  it: {
    eyebrow: "05 / Esperienza",
    heading: "Esperienza",
    supporting: "Ricerca, dati e software nella pratica.",
    timelineLabel: "Percorso professionale dal 2021 alla posizione attuale",
    pathCurrentLabel: "ATTUALE",
    pathOriginLabel: "INIZIO · 2021",
    currentRole: "Posizione attuale",
    responsibilitiesLabel: "Responsabilità",
    focusLabel: "Ambiti",
    roles: [
      {
        id: "safe",
        date: "Agosto 2026 – Presente",
        role: "Research Assistant",
        organization: "Leibniz Institute for Financial Research SAFE",
        location: "Francoforte sul Meno, Germania",
        responsibilities: [
          "Preparazione ed elaborazione di dati geospaziali e ambientali tramite workflow Python riproducibili.",
          "Supporto a workflow su larga scala per indirizzi, geocoding e collegamento di località a fini di ricerca.",
          "Collegamento di informazioni aziendali e territoriali con dati ambientali o di telerilevamento.",
          "Supporto a workflow di research computing per dataset spaziali più estesi.",
        ],
        focus: ["Python", "Data engineering geospaziale", "Dati ambientali", "Research computing"],
        current: true,
        pathLabel: "SAFE · Francoforte",
      },
      {
        id: "iip",
        date: "Luglio 2025 – Marzo 2026",
        role: "Analista GIS e dati, assistente di ricerca",
        organization: "IIP, Karlsruhe Institute of Technology (KIT)",
        location: "Karlsruhe, Germania",
        responsibilities: [
          "Sviluppo di pipeline Python per l'elaborazione di dati energetici e di mobilità.",
          "Analisi spaziali a supporto di modelli di domanda energetica e decarbonizzazione.",
          "Sviluppo di dashboard interattive con mappe integrate per flussi di ricerca applicata.",
        ],
        focus: ["Python", "Analisi spaziale", "Dati energia e mobilità", "Dashboard"],
        pathLabel: "IIP · KIT",
      },
      {
        id: "nova",
        date: "Luglio 2025 – Dicembre 2025",
        role: "Sviluppatore web, assistente di ricerca",
        organization: "KIT nova",
        location: "Karlsruhe, Germania",
        responsibilities: [
          "Contributo ad applicazioni web con attenzione a funzionalità e usabilità.",
          "Supporto a progetti VR/AR per applicazioni digitali e interattive.",
          "Contributo a visualizzazioni geospaziali e soluzioni cartografiche digitali.",
        ],
        focus: ["Applicazioni web", "VR/AR", "Geovisualizzazione", "Mappe digitali"],
        pathLabel: "KIT nova",
      },
      {
        id: "fartak",
        date: "Maggio 2021 – Settembre 2021",
        role: "Tirocinante",
        organization: "Naghsheh Gostaran Fartak Co.",
        responsibilities: [
          "Supporto a progetti di rilievo, fotogrammetria e GIS in un contesto operativo.",
          "Assistenza nella raccolta dati, nell'analisi spaziale e nell'implementazione tecnica.",
          "Uso di AutoCAD e strumenti GIS per creare ed elaborare dati geospaziali.",
        ],
        focus: ["Rilievo", "Fotogrammetria", "AutoCAD", "GIS"],
        pathLabel: "Fartak Co.",
      },
    ],
  },
};
