import type { HeroCopy, Locale } from "./hero.types";

export const heroCopy: Record<Locale, HeroCopy> = {
  en: {
    homeLabel: "Amirhossein Donyadidegan — home",
    languageLabel: "Language",
    navLabel: "Primary navigation",
    skipToIdentity: "Skip to identity",
    work: "Work",
    experience: "Experience",
    journey: "Education",
    stack: "Skills",
    contact: "Contact",
    quickCv: "Quick CV",
    skipIntro: "Skip intro",
    menu: "Open navigation",
    closeMenu: "Close navigation",
    role: "Geospatial Data & Software Engineer",
    tagline: "From coordinates to decisions.",
    exploreWork: "Explore work",
    downloadCv: "Download CV",
    metadataStates: [
      ["STATE 01", "COORDINATE"],
      ["STATE 02", "POINT FIELD"],
      ["STATE 03", "GRID"],
      ["STATE 04", "SPATIAL LAYERS"],
      ["STATE 05", "STRUCTURED DATA"],
      ["STATE 06", "MODEL"],
      ["STATE 07", "SYSTEM"],
      ["SYSTEM", "SPATIAL SYSTEMS"],
    ],
  },
  de: {
    homeLabel: "Amirhossein Donyadidegan — Startseite",
    languageLabel: "Sprache",
    navLabel: "Hauptnavigation",
    skipToIdentity: "Zur Identität springen",
    work: "Projekte",
    experience: "Erfahrung",
    journey: "Ausbildung",
    stack: "Kenntnisse",
    contact: "Kontakt",
    quickCv: "Kurzprofil",
    skipIntro: "Intro überspringen",
    menu: "Navigation öffnen",
    closeMenu: "Navigation schließen",
    role: "Ingenieur für Geodaten und Software",
    tagline: "Von Koordinaten zu Entscheidungen.",
    exploreWork: "Projekte ansehen",
    downloadCv: "Lebenslauf herunterladen",
    metadataStates: [
      ["STATUS 01", "KOORDINATE"],
      ["STATUS 02", "PUNKTFELD"],
      ["STATUS 03", "RASTER"],
      ["STATUS 04", "RÄUMLICHE EBENEN"],
      ["STATUS 05", "STRUKTURIERTE DATEN"],
      ["STATUS 06", "MODELL"],
      ["STATUS 07", "SYSTEM"],
      ["SYSTEM", "RÄUMLICHE SYSTEME"],
    ],
  },
  it: {
    homeLabel: "Amirhossein Donyadidegan — home",
    languageLabel: "Lingua",
    navLabel: "Navigazione principale",
    skipToIdentity: "Vai all’identità",
    work: "Progetti",
    experience: "Esperienza",
    journey: "Formazione",
    stack: "Competenze",
    contact: "Contatti",
    quickCv: "CV rapido",
    skipIntro: "Salta introduzione",
    menu: "Apri navigazione",
    closeMenu: "Chiudi navigazione",
    role: "Ingegnere di dati geospaziali e software",
    tagline: "Dalle coordinate alle decisioni.",
    exploreWork: "Vedi i progetti",
    downloadCv: "Scarica il CV",
    metadataStates: [
      ["STATO 01", "COORDINATA"],
      ["STATO 02", "CAMPO DI PUNTI"],
      ["STATO 03", "GRIGLIA"],
      ["STATO 04", "LAYER SPAZIALI"],
      ["STATO 05", "DATI STRUTTURATI"],
      ["STATO 06", "MODELLO"],
      ["STATO 07", "SISTEMA"],
      ["SISTEMA", "SISTEMI SPAZIALI"],
    ],
  },
};
