import type { Locale } from "../../sections/Hero/hero.types";

const en = {
  original: "Original map", generalized: "Generalized map", pair: "Study pair 1069",
  geometry: "Source geometry", features: "buildings", extent: "Shared extent", scale: "100 m",
  prompt: "Language", representation: "Features", classifier: "Classifier", operation: "Operation",
  mapPair: "Original and generalized building geometry from study pair 1069",
  dashboard: "Geoinformatics dashboard", reconstruction: "Documented state · reconstructed",
  city: "City", parameter: "Parameter", building: "Buildings", satellite: "Satellite context",
  floodRisk: "Buildings by flood risk", risk: "Flood risk", count: "Buildings", total: "Total",
  low: "Low", medium: "Medium", high: "High", source: "Source: SE4G design document · p. 14",
  sport: "Sport", venue: "Venue", skiing: "Men’s Alpine Skiing", skiMountaineering: "Ski Mountaineering", undefinedVenue: "To be defined",
  records: "Spatial records", database: "PostGIS", application: "Flask / Dash",
  terrain: "Terrain input", variables: "Environmental variables", model: "Random Forest", output: "Susceptibility",
  studyArea: "Study area", originalPalette: "Source color scale", input: "Input", result: "Output",
  dtm: "Digital terrain model", ndvi: "Vegetation · NDVI", slope: "Derived slope", confidence: "Classification confidence",
  reclassified: "Reclassified susceptibility", susceptibility: "Susceptibility surface", legend: "Legend",
  pipeline: "Terrain and environmental variables feed a Random Forest model to produce a landslide susceptibility surface. The terrain covers the wider source area; the output covers the outlined study area.",
  units: "Values as published", sourceMap: "Source map content", qgis: "QGIS · Dzetsaka",
};

export const projectVisualCopy: Record<Locale, typeof en> = {
  en,
  de: {
    ...en, original: "Originalkarte", generalized: "Generalisierte Karte", pair: "Studienpaar 1069",
    geometry: "Quellgeometrie", features: "Gebäude", extent: "Gleicher Ausschnitt",
    prompt: "Sprache", representation: "Merkmale", classifier: "Klassifikator", operation: "Operation",
    mapPair: "Ursprüngliche und generalisierte Gebäudegeometrie des Studienpaars 1069",
    dashboard: "Geoinformatik-Dashboard", reconstruction: "Dokumentierter Zustand · rekonstruiert",
    city: "Stadt", parameter: "Parameter", building: "Gebäude", satellite: "Satellitenkontext",
    floodRisk: "Gebäude nach Hochwasserrisiko", risk: "Hochwasserrisiko", count: "Gebäude", total: "Gesamt",
    low: "Niedrig", medium: "Mittel", high: "Hoch", source: "Quelle: SE4G-Designdokument · S. 14",
    sport: "Sportart", venue: "Austragungsort", skiing: "Ski Alpin der Herren", skiMountaineering: "Skibergsteigen", undefinedVenue: "Noch festzulegen",
    records: "Geodaten", terrain: "Geländeeingabe", variables: "Umweltvariablen", output: "Suszeptibilität",
    studyArea: "Untersuchungsgebiet", originalPalette: "Originale Farbskala", input: "Eingabe", result: "Ergebnis",
    dtm: "Digitales Geländemodell", ndvi: "Vegetation · NDVI", slope: "Hangneigung", confidence: "Klassifikationskonfidenz",
    reclassified: "Reklassifizierte Suszeptibilität", susceptibility: "Suszeptibilitätsfläche", legend: "Legende",
    pipeline: "Gelände- und Umweltvariablen fließen in ein Random-Forest-Modell ein. Die Geländekarte zeigt das größere Quellgebiet, das Ergebnis das umrandete Untersuchungsgebiet.",
    units: "Veröffentlichte Werte", sourceMap: "Originaler Karteninhalt",
  },
  it: {
    ...en, original: "Mappa originale", generalized: "Mappa generalizzata", pair: "Coppia di studio 1069",
    geometry: "Geometria sorgente", features: "edifici", extent: "Estensione condivisa",
    prompt: "Linguaggio", representation: "Caratteristiche", classifier: "Classificatore", operation: "Operazione",
    mapPair: "Geometria originale e generalizzata degli edifici della coppia di studio 1069",
    dashboard: "Dashboard geoinformatica", reconstruction: "Stato documentato · ricostruito",
    city: "Città", parameter: "Parametro", building: "Edifici", satellite: "Contesto satellitare",
    floodRisk: "Edifici per rischio alluvione", risk: "Rischio alluvione", count: "Edifici", total: "Totale",
    low: "Basso", medium: "Medio", high: "Alto", source: "Fonte: design document SE4G · p. 14",
    sport: "Sport", venue: "Sede", skiing: "Sci alpino maschile", skiMountaineering: "Sci alpinismo", undefinedVenue: "Da definire",
    records: "Dati spaziali", terrain: "Terreno in ingresso", variables: "Variabili ambientali", output: "Suscettibilità",
    studyArea: "Area di studio", originalPalette: "Scala cromatica originale", input: "Input", result: "Risultato",
    dtm: "Modello digitale del terreno", ndvi: "Vegetazione · NDVI", slope: "Pendenza derivata", confidence: "Confidenza della classificazione",
    reclassified: "Suscettibilità riclassificata", susceptibility: "Superficie di suscettibilità", legend: "Legenda",
    pipeline: "Terreno e variabili ambientali alimentano un modello Random Forest che produce una superficie di suscettibilità. Il terreno copre l’area sorgente più ampia; il risultato copre l’area di studio delimitata.",
    units: "Valori pubblicati", sourceMap: "Contenuto cartografico originale",
  },
};
